name: dropdown_below
description: flutter custom dropdown box. Develeoper can customize many options for there taste. It can be huge advantage for dropdown ux
version: 1.0.3
homepage: https://github.com/whatamelon/flutter_dropdown_below

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter_neumorphic: ^3.2.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
